name: connectivity_plus_extended
publish_to: 'none'
version: 1.0.0
repository: https://github.com/anthochamp/flutter-connectivity-plus-extended

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  anthochamp_dart_essentials: 
    git: git@github.com:anthochamp/dart-essentials.git
  async: ^2.10.0
  connectivity_plus: ^3.0.5
  inet_connectivity_checker: 
    git: git@github.com:anthochamp/dart-inet-connectivity-checker.git
  flutter: 
    sdk: flutter
  flutter_essentials: 
    git: git@github.com:anthochamp/flutter-essentials.git

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lints: ^2.0.1
